# Load used packages
library(tidyverse)
library(magrittr) 
library(raster) 
library(sf) 
library(spatstat) 
library(ncdf4)
library(fasterize) 
library(ggplot2) 
library(tmap) 
library(tmaptools) 
library(gdalUtils)
library(scico)
library(ggrepel)
library(rgdal)
library(RColorBrewer)
library(BAMMtools)